### ISSUE TITLE
Inconsistency in queue state

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-backend#122] opened 2021-02-20 19:25 UTC
I saw a case where I had a admin page link of a queue I used before and while opening it, I'm able to see the queue status and a member. When I tried to add a member or join this queue, I see that the request fails because apparently the queue has been deleted.

{"timestamp":"2021-02-20T19:17:14.694+0000","status":422,"error":"Unprocessable Entity","message":"The queue has been deleted","reasonCode":"QUEUE_DELETED"}

Another thing is if I try to create a queue with the same name, I see an error response saying that the queue name already exists. The queue name I see this for is 'dfgdgdfg' with queue id '8775a718-c26d-42af-a757-1e03a21014ae'.

Ideally if the queue is deleted, I would expect the admin page to not fetch data and have no restriction on creating another queue with the same name. On the flip side, if it's not deleted, I should be able to join and add members. This is on the main Simplq.me site.

**Comment by chalx** [comment] 2021-02-21 00:12
@maaverik This is normal to happen because we do not do a hard delete, just a soft delete. So we just update a status to deleted. 
1. So we can let to have same queue name, different id only if there not exists any other queue with the same name which has the state different from Deleted.
2. We can do a hard delete, but we can have an audit table for each generated queue.

**Comment by daltonfury42** [comment] 2021-02-21 05:40
I initially thought that the queue name is a unique identifier for somone's queue, and it's not to be reused. But, thinking more, in our context, it's a fair ask from @maaverik 

@chalx 2 looks safer and simpler as a concept, even though 1 might be easier to implement. If hibernate/we could handle [this](https://stackoverflow.com/questions/7844460/foreign-key-to-multiple-tables) well, we can go with 2, else fallback to 1.

**Comment by chalx** [comment] 2021-04-17 23:38
@daltonfury42 this can be closed because is duplicate of https://github.com/SimplQ/simplQ-backend/issues/126 which will fix this problem

**Closed** 2021-04-17 23:39 UTC
Labels: You can do this, good first issue
